version: '3'

services:
  frontend:
    container_name: frontend
    build:
      context: ./pinktdata-frontend
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3000:3000
    volumes:
      - ./pinktdata-frontend/src:/app/src

  backend:
    container_name: backend
    build:
      context: ./pinktada-backend
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 5000:5000
    volumes:
      - ./pinktada-backend/src:/app/src
